apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mongodb
  serviceName: mongodb
  template:
    metadata:
      labels:
        app: mongodb
        environment: test
    spec:
      containers:
      - image: mongo:v4.2.1
        name: mongodb
      - command:
        - mongod
        - --keyFile
        - mongo.keyfile
        - --bind_ip_all
        - 0.0.0.0
        - --replSet
        - rs0
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 27017
